# Generated by Django 2.2 on 2023-03-25 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230313_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=150, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁa-zA-Z\\s]+$', 'Поле может содержать только буквы')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=150, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁa-zA-Z\\s]+$', 'Поле может содержать только буквы')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁa-zA-Z\\s]+$', 'Поле может содержать только буквы')], verbose_name='Название'),
        ),
    ]
