# Generated by Django 2.2 on 2023-03-29 07:19

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230325_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[core.validators.validate_amount], verbose_name='Количество ингредиентов'),
        ),
    ]
