# Generated by Django 2.2 on 2023-03-15 15:59

import django.contrib.auth.validators
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), core.validators.validate_username], verbose_name='Логин'),
        ),
    ]
