# Generated by Django 2.2 on 2023-03-29 07:19

import core.validators
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230325_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁa-zA-Z\\s]+$', 'Поле может содержать только буквы')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁa-zA-Z\\s]+$', 'Поле может содержать только буквы')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), core.validators.validate_username], verbose_name='Логин'),
        ),
    ]
